kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-role-binding
  namespace: develop
subjects:
- kind: ServiceAccount
  name: bbpipelines
  namespace: develop
roleRef:
  kind: Role
  name: deploy
  apiGroup: rbac.authorization.k8s.io
