apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingresse-test
  namespace: develop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8-ingress.auto.pink.cat 
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /
